name: Backend CI/CD

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
  push:
    branches: [ main, dev ]
    paths:
      - 'backend/**'

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build Backend
        run: |
          cd backend
          dotnet build --configuration Release

      - name: Run Tests
        run: |
          cd backend
          dotnet test --no-build --verbosity normal
      # Optionally add deployment steps here
