name: Frontend CI/CD

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'frontend/**'
  push:
    branches: [ main, dev ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
      # Optionally add deployment steps here
